### PR TITLE
Ability to specify list of engine.io transports through the SIOSocket client.

### LINKED ISSUE #35: Specify transports
I use the following JavaScript code to over-ride the default `transports` setting to only use `websocket`.

    var socket = io('http://localhost:8080/user-data-sync', {
      transports: [ 'websocket' ]
    });

Is this possible with the SIOSocket client?  This is a big deal for a project that I am working on where the client and server both support WebSockets, but there are technical reasons to avoid doing the handshake over long-polling.

### PR DESCRIPTION
**Pull request by brandonramirez**
Resolves #35

### CODE REVIEW

**Comment by gtomitsuka** [comment]
+1. Helps a lot.

**Comment by agconti** [comment]
+1. We found this ourselves. Its necessary for sockets to properly connect to servers running more than one dyno.

**Comment by glemmaPaul** [comment]
+1. This also resolves a lot of problems with 2 dyno's on Heroku. I have to force the socket.io client to use `websocket`. Please merge this in.

**Comment by frandrzej** [comment]
Amazing, thanks guys! To solve the problem of 2 dyno's on Heroku, I had to use only "websocket" transports. Also in socket.io.js.h there was one argument missing (NSArray *transports) and I couldn't compile because of it

```
static NSString *socket_io_js_constructor(NSString *hostURL, BOOL reconnection, NSInteger attemptLimit, NSTimeInterval reconnectionDelay, NSTimeInterval reconnectionDelayMax, NSTimeInterval timeout, NSArray *transports) { 
    ... 
}

```

**Comment by glemmaPaul** [comment]
Exactly, the `transports` need to be on `websockets` to not let it fail connecting. The cause of it can be because of the long polling functionality on the beginning. The router fails to keep it on one web dyno.


On Saturday, Feb 14, 2015 at 12:04 PM, frandrzej <notifications@github.com>, wrote:

Amazing, thanks guys! To solve the problem of 2 dyno's on Heroku, I had to use only "websocket" transports. Also in socket.io.js.h there was one argument missing (NSArray *transports) and I couldn't compile because of it


static NSString *socket_io_js_constructor(NSString *hostURL, BOOL reconnection, NSInteger attemptLimit, NSTimeInterval reconnectionDelay, NSTimeInterval reconnectionDelayMax, NSTimeInterval timeout, NSArray *transports) { 
    ... 
}

**Pull request merged**
